#pragma once

#include <Windows.h>

class Menus {
public:

	static const int
		IDM_MAIN_FILE_LOAD_ROM = 1,
		IDM_MAIN_FILE_SAVE_STATE = 2,
		IDM_MAIN_FILE_LOAD_STATE = 3,
		IDM_MAIN_FILE_QUIT = 4,

		IDM_MAIN_EMULATION_PAUSE = 5,
		IDM_MAIN_EMULATION_RESET = 6,
		IDM_MAIN_EMULATION_SPEED_1 = 7,
		IDM_MAIN_EMULATION_SPEED_2 = 8,
		IDM_MAIN_EMULATION_SPEED_5 = 9,
		IDM_MAIN_EMULATION_SPEED_10 = 10,

		IDM_MAIN_VIEW_WINDOW_SIZE_100 = 11,
		IDM_MAIN_VIEW_WINDOW_SIZE_200 = 12,
		IDM_MAIN_VIEW_WINDOW_SIZE_300 = 13,
		IDM_MAIN_VIEW_WINDOW_SIZE_400 = 14,
		IDM_MAIN_VIEW_WINDOW_SIZE_500 = 15,
		IDM_MAIN_VIEW_TILES = 16,
		IDM_MAIN_VIEW_DEBUG = 17,
		IDM_MAIN_VIEW_COLOR_CLASSIC = 18,
		IDM_MAIN_VIEW_COLOR_GRAYSCALE = 19,
		IDM_MAIN_VIEW_BACKGROUND_MAP = 20;

	static HMENU menuBar;
	static HMENU fileMenu, emulationMenu, viewMenu;

	static HMENU CreateMainWindowMenus();
};

